import {
  blusa, cila3, cila4, cila8, cila9, cila11,
  cila14, cila17, cila20, cila23, cila24, cila26,
  cila31, cila32, cila33, cila34, cila37, cila45,
} from "./images/index";

const CATEGORY_TOPS = "Tops";
const CATEGORY_BOTTOMS = "Bottoms";
const CATEGORY_VESTIDOS = "Vestidos";
const CATEGORY_NOVEDADES = "Novedades";

const products = [
  {
    id: 1,
    name: "Blusa Clásica",
    productType: "Blusa",
    category: CATEGORY_TOPS,
    price: 22000,
    image: blusa,
    images: [blusa, cila11, cila17],
    colors: ["Blanco", "Negro", "Rosa"],
    sizes: ["S", "M", "L"],
    description: "Blusa versátil de corte clásico, ideal para combinar con cualquier outfit.",
    quantity: 1,
  },
  {
    id: 2,
    name: "Camiseta Oversize",
    productType: "Camiseta",
    category: CATEGORY_TOPS,
    price: 22000,
    image: cila3,
    images: [cila3, cila20, cila24],
    colors: ["Negro", "Blanco", "Gris"],
    sizes: ["S", "M", "L", "XL"],
    description: "Camiseta oversize con caída relajada. Comodidad y estilo urbano.",
    quantity: 1,
  },
  {
    id: 3,
    name: "Jean Tiro Alto",
    productType: "Jean",
    category: CATEGORY_BOTTOMS,
    price: 70000,
    image: cila4,
    images: [cila4, cila14, cila31],
    colors: ["Azul", "Negro", "Celeste"],
    sizes: ["26", "28", "30", "32"],
    description: "Jean de tiro alto con ajuste perfecto. Denim premium de alta calidad.",
    quantity: 1,
  },
  {
    id: 4,
    name: "Vestido Asimétrico",
    productType: "Vestido",
    category: CATEGORY_VESTIDOS,
    price: 50000,
    image: cila8,
    images: [cila8, cila9, cila23],
    colors: ["Negro", "Rojo", "Verde"],
    sizes: ["S", "M", "L"],
    description: "Vestido de corte asimétrico con diseño moderno y elegante.",
    quantity: 1,
  },
  {
    id: 5,
    name: "Vestido Strapless",
    productType: "Vestido",
    category: CATEGORY_VESTIDOS,
    price: 50000,
    image: cila9,
    images: [cila9, cila8, cila26],
    colors: ["Negro", "Blanco", "Azul"],
    sizes: ["S", "M", "L"],
    description: "Vestido strapless perfecto para eventos y salidas nocturnas.",
    quantity: 1,
  },
  {
    id: 6,
    name: "Blusa Escote V",
    productType: "Blusa",
    category: CATEGORY_TOPS,
    price: 35000,
    image: cila11,
    images: [cila11, cila17, cila20],
    colors: ["Negro", "Rojo", "Blanco"],
    sizes: ["S", "M", "L"],
    description: "Blusa con escote en V y acabado premium. Elegancia casual.",
    quantity: 1,
  },
  {
    id: 7,
    name: "Jean Bota Ancha",
    productType: "Jean",
    category: CATEGORY_BOTTOMS,
    price: 65000,
    image: cila14,
    images: [cila14, cila4, cila31],
    colors: ["Azul oscuro", "Negro", "Azul claro"],
    sizes: ["26", "28", "30", "32"],
    description: "Jean de bota ancha con estilo retro y corte favorecedor.",
    quantity: 1,
  },
  {
    id: 8,
    name: "Blusa Rosa",
    productType: "Blusa",
    category: CATEGORY_NOVEDADES,
    price: 32000,
    image: cila17,
    images: [cila17, cila33, cila34],
    colors: ["Rosa", "Negro", "Blanco"],
    sizes: ["S", "M", "L"],
    description: "Blusa en tono rosa con diseño fresco y juvenil.",
    quantity: 1,
  },
  {
    id: 9,
    name: "Top Básico",
    productType: "Top",
    category: CATEGORY_TOPS,
    price: 25000,
    image: cila20,
    images: [cila20, cila37, cila45],
    colors: ["Negro", "Blanco", "Gris"],
    sizes: ["S", "M", "L"],
    description: "Top básico esencial para cualquier guardarropa. Tela suave y cómoda.",
    quantity: 1,
  },
  {
    id: 10,
    name: "Vestido Casual",
    productType: "Vestido",
    category: CATEGORY_VESTIDOS,
    price: 48000,
    image: cila23,
    images: [cila23, cila8, cila26],
    colors: ["Beige", "Negro", "Azul"],
    sizes: ["S", "M", "L"],
    description: "Vestido casual para el día a día. Cómodo y con estilo.",
    quantity: 1,
  },
  {
    id: 11,
    name: "Crop Top",
    productType: "Top",
    category: CATEGORY_TOPS,
    price: 28000,
    image: cila24,
    images: [cila24, cila33, cila34],
    colors: ["Blanco", "Negro", "Beige"],
    sizes: ["S", "M", "L"],
    description: "Crop top moderno, perfecto para combinar con jeans de tiro alto.",
    quantity: 1,
  },
  {
    id: 12,
    name: "Vestido Midi",
    productType: "Vestido",
    category: CATEGORY_VESTIDOS,
    price: 55000,
    image: cila26,
    images: [cila26, cila23, cila9],
    colors: ["Negro", "Verde", "Terracota"],
    sizes: ["S", "M", "L"],
    description: "Vestido midi elegante con corte favorecedor para cualquier ocasión.",
    quantity: 1,
  },
  {
    id: 13,
    name: "Pantalón Palazzo",
    productType: "Pantalón",
    category: CATEGORY_BOTTOMS,
    price: 60000,
    image: cila31,
    images: [cila31, cila14, cila4],
    colors: ["Negro", "Beige", "Gris"],
    sizes: ["S", "M", "L"],
    description: "Pantalón palazzo de pierna ancha. Comodidad con elegancia.",
    quantity: 1,
  },
  {
    id: 14,
    name: "Body Clásico",
    productType: "Body",
    category: CATEGORY_NOVEDADES,
    price: 30000,
    image: cila32,
    images: [cila32, cila33, cila37],
    colors: ["Negro", "Rojo", "Blanco"],
    sizes: ["S", "M", "L"],
    description: "Body clásico con ajuste perfecto al cuerpo. Base ideal para cualquier look.",
    quantity: 1,
  },
  {
    id: 15,
    name: "Top Cuello Alto",
    productType: "Top",
    category: CATEGORY_TOPS,
    price: 30000,
    image: cila33,
    images: [cila33, cila34, cila37],
    colors: ["Negro", "Blanco", "Café"],
    sizes: ["S", "M", "L"],
    description: "Top de cuello alto con tela suave y ajustada. Ideal para clima fresco.",
    quantity: 1,
  },
  {
    id: 16,
    name: "Top Cuello Redondo",
    productType: "Top",
    category: CATEGORY_NOVEDADES,
    price: 27000,
    image: cila34,
    images: [cila34, cila33, cila45],
    colors: ["Blanco", "Negro", "Azul"],
    sizes: ["S", "M", "L", "XL"],
    description: "Top cuello redondo de corte limpio. Básico imprescindible.",
    quantity: 1,
  },
  {
    id: 17,
    name: "Top de Encaje",
    productType: "Top",
    category: CATEGORY_TOPS,
    price: 35000,
    image: cila37,
    images: [cila37, cila33, cila45],
    colors: ["Negro", "Blanco", "Rosa"],
    sizes: ["S", "M", "L"],
    description: "Top con detalles de encaje. Sofisticado y femenino.",
    quantity: 1,
  },
  {
    id: 18,
    name: "Top Sin Mangas",
    productType: "Top",
    category: CATEGORY_TOPS,
    price: 24000,
    image: cila45,
    images: [cila45, cila34, cila24],
    colors: ["Blanco", "Negro", "Azul"],
    sizes: ["S", "M", "L"],
    description: "Top sin mangas fresco y ligero. Perfecto para el verano.",
    quantity: 1,
  },
];

export const CATEGORIES = [
  { name: CATEGORY_TOPS, path: "/categoria/tops" },
  { name: CATEGORY_BOTTOMS, path: "/categoria/bottoms" },
  { name: CATEGORY_VESTIDOS, path: "/categoria/vestidos" },
  { name: CATEGORY_NOVEDADES, path: "/categoria/novedades" },
];

export default products;
